name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build -W -b html -d site/_build/doctrees site site/_build/html
      - name: Sphinx link test
        run: |
          sphinx-build -W -b linkcheck -d site/_build/doctrees site site/_build/linkcheck
